notifications:
  email: false
env:
  - RELEASE_BRANCH="master"
language: c
os:
- linux
- osx
sudo: required
services:
  - docker

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull dyne/devuan:beowulf && docker build -t freior/pugins .; fi

script:
- cmake . && make -j && sudo make install
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clean -fd && ./autogen.sh && ./configure && make -j && sudo make install ; fi
