notifications:
  email: false
env:
  - RELEASE_BRANCH="master"
language: c
os:
- linux
- osx
sudo: required
services:
  - docker

before_install:
- docker pull dyne/devuan:beowulf
- docker build -t freior/pugins .

script:
- cmake . && make
